// packages/nextjs-example/app/_components/BankDemo.tsx
"use client";

import { useMemo, useState, useEffect } from "react";
import { useAccount } from "wagmi";
import { RainbowKitCustomConnectButton } from "~~/components/helper/RainbowKitCustomConnectButton";
import { FHEVMProvider, useFHEVM, useFHEVMSignature, useFHEDecrypt, useInMemoryStorage, logger } from "@fhevm/sdk/react";
import { ethers } from "ethers";
import { useReadContract, useWriteContract } from "wagmi";
import { getContractConfig } from "~~/contracts";

/**
 * FHE Bank Demo using Universal FHEVM SDK
 * 
 * This component demonstrates confidential banking operations:
 * - Deposit encrypted amounts
 * - Withdraw encrypted amounts  
 * - Transfer between users
 * - View encrypted balances
 */
function BankDemoContent() {
  const { isConnected, chain, address } = useAccount();
  const chainId = chain?.id;

  // Contract configuration
  const bankConfig = getContractConfig('FHEBank');

  // FHEVM configuration
  const fhevmConfig = useMemo(() => ({
    rpcUrl: chainId === 31337 ? "http://localhost:8545" : process.env.NEXT_PUBLIC_ALCHEMY_API_KEY ? `https://eth-sepolia.g.alchemy.com/v2/${process.env.NEXT_PUBLIC_ALCHEMY_API_KEY}` : `https://sepolia.infura.io/v3/${process.env.NEXT_PUBLIC_INFURA_API_KEY}`,
    chainId: chainId || Number(process.env.NEXT_PUBLIC_CHAIN_ID) || 11155111,
    mockChains: {
      31337: "http://localhost:8545"
    }
  }), [chainId]);

  // FHEVM hooks - REAL IMPLEMENTATION
  const { instance, isInitialized: isReady, status, error: fhevmError } = useFHEVM(fhevmConfig);

  // Generate public key for encryption
  const publicKey = useMemo(() => {
    if (instance && isReady) {
      try {
        const keypair = instance.generateKeypair();
        return keypair.publicKey;
      } catch (error) {
        logger.error("Failed to generate keypair", error);
        return null;
      }
    }
    return null;
  }, [instance, isReady]);

  // EIP-712 signature hook for decryption
  const { generateSignature, signature, isSigning, error: signatureError } = useFHEVMSignature(instance, address);

  // Create ethers signer from window.ethereum (same as contract operations use)
  const ethersSigner = useMemo(() => {
    if (!isConnected || !address) return undefined;
    
    try {
      // Use the same ethereum provider that Wagmi uses
      const provider = new ethers.BrowserProvider((window as any).ethereum);
      const signer = new ethers.JsonRpcSigner(provider, address);
      
      return signer;
    } catch (error) {
      logger.error('Failed to create ethers signer', error);
      return undefined;
    }
  }, [isConnected, address]);

  // Contract interactions (like Vue version - always disabled initially)
  const { data: fetchedBalance, refetch: refetchBalance, error: fetchBalanceError } = useReadContract({
    address: bankConfig.address as `0x${string}`,
    abi: bankConfig.abi as any,
    functionName: "getEncryptedBalance",
    args: [address as `0x${string}`],
    query: {
      enabled: false, // Always disabled initially, fetch manually
      refetchOnWindowFocus: false,
    },
  });

  const { data: fetchedTotalSupply, refetch: refetchTotalSupply, error: fetchTotalSupplyError } = useReadContract({
    address: bankConfig.address as `0x${string}`,
    abi: bankConfig.abi as any,
    functionName: "getEncryptedTotalSupply",
    query: {
      enabled: false, // Always disabled initially, fetch manually
      refetchOnWindowFocus: false,
    },
  });

  // In-memory storage for decryption signatures
  const fhevmDecryptionSignatureStorage = useInMemoryStorage();

  const { writeContract: writeBank, isPending: isWritePending, error: writeError, isSuccess: isWriteSuccess, reset: resetWrite } = useWriteContract();

  // State
  const [message, setMessage] = useState<string>("");
  const [isProcessing, setIsProcessing] = useState(false);
  const [amount, setAmount] = useState<string>("100");
  
  // Separate state for balance handle (like Vue version)
  const [balanceHandle, setBalanceHandle] = useState<string | null>(null);
  const [totalSupplyHandle, setTotalSupplyHandle] = useState<string | null>(null);

  // Decryption requests for signature-based decryption
  const requests = useMemo(() => {
    if (!bankConfig.address) return undefined;
    
    const requestList = [];
    if (balanceHandle && balanceHandle !== "0x0000000000000000000000000000000000000000000000000000000000000000") {
      requestList.push({ 
        handle: balanceHandle.toString(), 
        contractAddress: bankConfig.address as `0x${string}` 
      });
    }
    if (totalSupplyHandle && totalSupplyHandle !== "0x0000000000000000000000000000000000000000000000000000000000000000") {
      requestList.push({ 
        handle: totalSupplyHandle.toString(), 
        contractAddress: bankConfig.address as `0x${string}` 
      });
    }
    
    return requestList.length > 0 ? requestList : undefined;
  }, [bankConfig.address, balanceHandle, totalSupplyHandle]);

  // FHEVM Decryption using signature-based approach
  const {
    canDecrypt,
    decrypt: performDecrypt,
    isDecrypting,
    message: decryptionMessage,
    results,
    error: decryptError
  } = useFHEDecrypt({
    instance,
    ethersSigner,
    fhevmDecryptionSignatureStorage: fhevmDecryptionSignatureStorage.storage,
    requests
  });

  // Watch for changes in fetchedBalance and update balanceHandle (like Vue version)
  useEffect(() => {
    if (fetchedBalance) {
      setBalanceHandle(fetchedBalance as string);
    }
  }, [fetchedBalance]);

  // Watch for changes in fetchedTotalSupply and update totalSupplyHandle (like Vue version)
  useEffect(() => {
    if (fetchedTotalSupply) {
      setTotalSupplyHandle(fetchedTotalSupply as string);
    }
  }, [fetchedTotalSupply]);

  logger.debug("Bank Current state", {
    balanceHandle,
    totalSupplyHandle,
    resultsKeys: Object.keys(results),
    currentBalance: balanceHandle ? results?.[balanceHandle.toString()] : null,
    currentTotalSupply: totalSupplyHandle ? results?.[totalSupplyHandle.toString()] : null,
    // Debug decryption dependencies
    hasInstance: Boolean(instance),
    hasEthersSigner: Boolean(ethersSigner),
    hasRequests: Boolean(requests),
    requestsLength: requests?.length,
    canDecrypt,
    isDecrypting
  });
  const [recipient, setRecipient] = useState<string>("");

  // Manual balance fetch function (like Vue version)
  const fetchBalanceHandle = async () => {
    if (!bankConfig.address || !isReady || !address) {
      return;
    }

    try {
      await refetchBalance();
    } catch (error) {
      logger.error("Failed to fetch encrypted balance handle", error);
    }
  };

  // Handlers
  const handleDeposit = async () => {
    if (!instance || !bankConfig.address || !address) return;
    
    setIsProcessing(true);
    setMessage("Depositing to bank...");
    
    try {
      const amountNum = parseInt(amount);
      if (isNaN(amountNum) || amountNum <= 0) {
        setMessage("Please enter a valid amount");
        return;
      }

      // Create encrypted input using FHEVM pattern
      setMessage("Creating encrypted input...");
      const input = instance.createEncryptedInput(bankConfig.address, address);
      input.add64(amountNum); // Deposit amount (64-bit for FHEBank contract)
      const encryptedResult = await input.encrypt();
      
      if (!encryptedResult || !encryptedResult.handles || !encryptedResult.handles[0]) {
        throw new Error("Encryption failed - no handle returned");
      }
      
      if (!encryptedResult.inputProof) {
        throw new Error("Encryption failed - no inputProof returned");
      }
      
      // Convert to hex strings
      const toHex = (data: Uint8Array) => {
        return '0x' + Array.from(data).map(b => b.toString(16).padStart(2, '0')).join('');
      };
      
      const externalEuint64 = toHex(encryptedResult.handles[0]);
      const inputProof = toHex(encryptedResult.inputProof);
      
      setMessage(`Encrypted: ${externalEuint64.slice(0, 20)}...`);
      
      // Reset any previous write state (like Vue version)
      resetWrite();
      
      // Call the contract
      setMessage("📝 Signing transaction...");
      await writeBank({
        address: bankConfig.address as `0x${string}`,
        abi: bankConfig.abi as any,
        functionName: 'deposit',
        args: [externalEuint64, inputProof], // encrypted amount and proof (64-bit)
        gas: 2000000n, // Set gas limit
        gasPrice: 20000000000n, // 20 gwei for Sepolia
      });
      
      setMessage(`Deposited ${amountNum}! Refreshing balance...`);
      
      // Wait for transaction to be confirmed
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // Fetch balance handle after successful transaction (like Vue version)
      await fetchBalanceHandle();
      await refetchTotalSupply();
    } catch (error) {
      setMessage(`Deposit failed: ${error instanceof Error ? error.message : String(error)}`);
    } finally {
      setIsProcessing(false);
    }
  };

  const handleWithdraw = async () => {
    if (!instance || !bankConfig?.address || !address) return;
    
    setIsProcessing(true);
    setMessage("Withdrawing from bank...");
    
    try {
      const amountNum = parseInt(amount);
      if (isNaN(amountNum) || amountNum <= 0) {
        setMessage("Please enter a valid amount");
        return;
      }

      // Create encrypted input using FHEVM pattern
      setMessage("Creating encrypted input...");
      const input = instance.createEncryptedInput(bankConfig.address, address);
      input.add64(amountNum); // Withdraw amount (64-bit for FHEBank contract)
      const encryptedResult = await input.encrypt();
      
      if (!encryptedResult || !encryptedResult.handles || !encryptedResult.handles[0]) {
        throw new Error("Encryption failed - no handle returned");
      }
      
      if (!encryptedResult.inputProof) {
        throw new Error("Encryption failed - no inputProof returned");
      }
      
      // Convert to hex strings
      const toHex = (data: Uint8Array) => {
        return '0x' + Array.from(data).map(b => b.toString(16).padStart(2, '0')).join('');
      };
      
      const externalEuint64 = toHex(encryptedResult.handles[0]);
      const inputProof = toHex(encryptedResult.inputProof);
      
      setMessage(`Withdrawing ${amountNum} (encrypted: ${externalEuint64.slice(0, 20)}...)`);
      
      // Reset any previous write state (like Vue version)
      resetWrite();
      
      // Call the contract
      setMessage("📝 Signing transaction...");
      await writeBank({
        address: bankConfig.address as `0x${string}`,
        abi: bankConfig.abi as any,
        functionName: 'withdraw',
        args: [externalEuint64, inputProof], // encrypted amount and proof (64-bit)
        gas: 2000000n, // Set gas limit
        gasPrice: 20000000000n, // 20 gwei for Sepolia
      });
      
      setMessage("Withdrawal completed successfully!");
      
      // Wait for transaction to be confirmed
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // Fetch balance handle after successful transaction (like Vue version)
      await fetchBalanceHandle();
      await refetchTotalSupply();
    } catch (error) {
      setMessage(`Withdrawal failed: ${error instanceof Error ? error.message : String(error)}`);
    } finally {
      setIsProcessing(false);
    }
  };

  const handleTransfer = async () => {
    if (!instance || !bankConfig?.address || !recipient || !address) return;
    
    setIsProcessing(true);
    setMessage("Transferring funds...");
    
    try {
      const amountNum = parseInt(amount);
      if (isNaN(amountNum) || amountNum <= 0) {
        setMessage("Please enter a valid amount");
        return;
      }

      if (!recipient.startsWith("0x") || recipient.length !== 42) {
        setMessage("Please enter a valid recipient address");
        return;
      }

      // Create encrypted input using FHEVM pattern
      setMessage("Creating encrypted input...");
      const input = instance.createEncryptedInput(bankConfig.address, address);
      input.add64(amountNum); // Transfer amount (64-bit for FHEBank contract)
      const encryptedResult = await input.encrypt();
      
      if (!encryptedResult || !encryptedResult.handles || !encryptedResult.handles[0]) {
        throw new Error("Encryption failed - no handle returned");
      }
      
      if (!encryptedResult.inputProof) {
        throw new Error("Encryption failed - no inputProof returned");
      }
      
      // Convert to hex strings
      const toHex = (data: Uint8Array) => {
        return '0x' + Array.from(data).map(b => b.toString(16).padStart(2, '0')).join('');
      };
      
      const externalEuint64 = toHex(encryptedResult.handles[0]);
      const inputProof = toHex(encryptedResult.inputProof);
      
      setMessage(`Transferring ${amountNum} to ${recipient} (encrypted: ${externalEuint64.slice(0, 20)}...)`);
      
      // Reset any previous write state (like Vue version)
      resetWrite();
      
      // Call the contract
      setMessage("📝 Signing transaction...");
      await writeBank({
        address: bankConfig.address as `0x${string}`,
        abi: bankConfig.abi as any,
        functionName: 'transfer',
        args: [recipient, externalEuint64, inputProof], // recipient, encrypted amount and proof (64-bit)
        gas: 2000000n, // Set gas limit
        gasPrice: 20000000000n, // 20 gwei for Sepolia
      });
      
      setMessage("Transfer completed successfully!");
      
      // Wait for transaction to be confirmed
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // Fetch balance handle after successful transaction (like Vue version)
      await fetchBalanceHandle();
    } catch (error) {
      setMessage(`Transfer failed: ${error instanceof Error ? error.message : String(error)}`);
    } finally {
      setIsProcessing(false);
    }
  };

  const handleDecryptBalance = async () => {
    if (!balanceHandle || balanceHandle === "0x0000000000000000000000000000000000000000000000000000000000000000") {
      setMessage("No balance data to decrypt");
      return;
    }

    if (!instance || !bankConfig.address || !address) {
      setMessage("FHEVM not ready");
      return;
    }

    if (!canDecrypt) {
      setMessage("⚠️ Cannot decrypt - missing dependencies (signer, instance, or requests)");
      return;
    }

    setIsProcessing(true);
    setMessage("Decrypting balance...");

    try {
      await performDecrypt();
      await new Promise(resolve => setTimeout(resolve, 100));
      
      const handleKey = balanceHandle.toString();
      const decryptedValue = results?.[handleKey];
      
      if (decryptedValue !== undefined) {
        setMessage(`Your balance: ${decryptedValue}`);
      } else {
        setMessage("Decryption completed but no result found");
      }
    } catch (error) {
      setMessage(`Balance decryption failed: ${error instanceof Error ? error.message : String(error)}`);
    } finally {
      setIsProcessing(false);
    }
  };

  if (!isConnected) {
    return (
      <div className="max-w-6xl mx-auto p-6 text-gray-900">
        <div className="flex items-center justify-center">
          <div className="bg-white border shadow-xl p-8 text-center">
            <div className="mb-4">
              <span className="inline-flex items-center justify-center w-14 h-14 rounded-full bg-blue-900/30 text-blue-400 text-3xl">
                🏦
              </span>
            </div>
            <h2 className="text-2xl font-extrabold text-gray-900 mb-2">Wallet not connected</h2>
            <p className="text-gray-700 mb-6">Connect your wallet to use the FHE Bank demo.</p>
            <div className="flex items-center justify-center">
              <RainbowKitCustomConnectButton />
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto p-6 space-y-6 text-gray-900">
      {/* Header */}
      <div className="text-center mb-8 text-black">
        <h1 className="text-3xl font-bold mb-2">🏦 FHE Bank Demo</h1>
        <p className="text-gray-600">Confidential banking with encrypted deposits, withdrawals, and transfers</p>
      </div>

      {/* Your Balance - Prioritized */}
      <div className="bg-gradient-to-r from-green-50 to-blue-50 shadow-lg p-6 mb-6 text-gray-900 border-2 border-green-200">
        <h3 className="font-bold text-gray-900 text-xl mb-4 border-b-2 border-green-300 pb-2">💰 Your Balance</h3>
        <div className="text-center">
          <div className="text-4xl font-bold text-green-600 mb-2">
            {balanceHandle ? (results?.[balanceHandle.toString()] || "Encrypted") : "No balance"}
          </div>
          <p className="text-gray-600 text-sm">
            {balanceHandle ? "Decrypted balance" : "Connect wallet and fetch balance to see your funds"}
          </p>
        </div>
      </div>

      {/* FHEVM Status - Simplified */}
      <div className="bg-[#f4f4f4] shadow-lg p-6 mb-6 text-gray-900">
        <h3 className="font-bold text-gray-900 text-xl mb-4 border-b-1 border-gray-700 pb-2">🔧 Bank Status</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="space-y-3">
            {printProperty("Status", status)}
            {printProperty("Ready", isReady ? "✅ Yes" : "❌ No")}
            {printProperty("Error", fhevmError ? (fhevmError as Error).message : "None")}
          </div>
          <div className="space-y-3">
            {printProperty("Contract Address", bankConfig?.address || "Not deployed")}
            {printProperty("Your Address", address || "Not connected")}
            {printProperty("Balance Handle", balanceHandle ? `${balanceHandle.slice(0, 8)}...${balanceHandle.slice(-8)}` : "No balance")}
          </div>
        </div>
      </div>

      {/* Bank Operations */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Deposit */}
        <div className="bg-white border shadow-lg p-6">
          <h3 className="text-xl font-bold mb-4 text-gray-900">💰 Deposit</h3>
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Amount</label>
              <input
                type="number"
                value={amount}
                onChange={(e) => setAmount(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="Enter amount to deposit"
              />
            </div>
            <button
              className="w-full bg-green-600 text-white py-2 px-4 rounded-md hover:bg-green-700 disabled:opacity-50 disabled:cursor-not-allowed"
              disabled={!isReady || isProcessing}
              onClick={handleDeposit}
            >
              {isProcessing ? "⏳ Processing..." : "💰 Deposit"}
            </button>
          </div>
        </div>

        {/* Withdraw */}
        <div className="bg-white border shadow-lg p-6">
          <h3 className="text-xl font-bold mb-4 text-gray-900">💸 Withdraw</h3>
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Amount</label>
              <input
                type="number"
                value={amount}
                onChange={(e) => setAmount(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="Enter amount to withdraw"
              />
            </div>
            <button
              className="w-full bg-red-600 text-white py-2 px-4 rounded-md hover:bg-red-700 disabled:opacity-50 disabled:cursor-not-allowed"
              disabled={!isReady || isProcessing}
              onClick={handleWithdraw}
            >
              {isProcessing ? "⏳ Processing..." : "💸 Withdraw"}
            </button>
          </div>
        </div>

        {/* Transfer */}
        <div className="bg-white border shadow-lg p-6">
          <h3 className="text-xl font-bold mb-4 text-gray-900">🔄 Transfer</h3>
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Recipient Address</label>
              <input
                type="text"
                value={recipient}
                onChange={(e) => setRecipient(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="0x..."
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Amount</label>
              <input
                type="number"
                value={amount}
                onChange={(e) => setAmount(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="Enter amount to transfer"
              />
            </div>
            <button
              className="w-full bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
              disabled={!isReady || isProcessing || !recipient}
              onClick={handleTransfer}
            >
              {isProcessing ? "⏳ Processing..." : "🔄 Transfer"}
            </button>
          </div>
        </div>

        {/* View Balance */}
        <div className="bg-white border shadow-lg p-6">
          <h3 className="text-xl font-bold mb-4 text-gray-900">👁️ View Balance</h3>
          <div className="space-y-4">
            <p className="text-gray-600">Decrypt your encrypted balance</p>
            <div className="flex space-x-2">
              <button
                className="flex-1 bg-purple-600 text-white py-2 px-4 rounded-md hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed"
                disabled={!balanceHandle || isDecrypting}
                onClick={handleDecryptBalance}
              >
                {isDecrypting ? "⏳ Decrypting..." : "👁️ Decrypt Balance"}
              </button>
              <button
                className="flex-1 bg-gray-600 text-white py-2 px-4 rounded-md hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed"
                disabled={!isConnected}
                onClick={fetchBalanceHandle}
              >
                🔄 Get Balance
              </button>
            </div>
          </div>
        </div>
      </div>


      {/* Errors */}
      {(decryptError || signatureError) && (
        <div className="bg-red-50 border border-red-200 p-4 rounded-lg">
          <h3 className="font-bold text-red-800 text-lg mb-2">❌ Errors</h3>
          {decryptError && <p className="text-red-700">Decrypt: {(decryptError as Error).message}</p>}
          {signatureError && <p className="text-red-700">Signature: {(signatureError as Error).message}</p>}
        </div>
      )}
    </div>
  );
}

/**
 * Bank Demo with Universal SDK Provider
 */
export function BankDemo() {
  return (
    <FHEVMProvider config={{
      rpcUrl: process.env.NEXT_PUBLIC_ALCHEMY_API_KEY ? `https://eth-sepolia.g.alchemy.com/v2/${process.env.NEXT_PUBLIC_ALCHEMY_API_KEY}` : `https://sepolia.infura.io/v3/${process.env.NEXT_PUBLIC_INFURA_API_KEY}`,
      chainId: Number(process.env.NEXT_PUBLIC_CHAIN_ID) || 11155111,
      mockChains: {
        31337: "http://localhost:8545"
      }
    }}>
      <BankDemoContent />
    </FHEVMProvider>
  );
}

function printProperty(name: string, value: unknown) {
  let displayValue: string;

  if (typeof value === "boolean") {
    return printBooleanProperty(name, value);
  } else if (typeof value === "string" || typeof value === "number") {
    displayValue = String(value);
  } else if (typeof value === "bigint") {
    displayValue = String(value);
  } else if (value === null) {
    displayValue = "null";
  } else if (value === undefined) {
    displayValue = "undefined";
  } else if (value instanceof Error) {
    displayValue = value.message;
  } else {
    displayValue = JSON.stringify(value);
  }
  return (
    <div className="flex justify-between items-center py-2 px-3 bg-white border border-gray-200 w-full">
      <span className="text-gray-800 font-medium">{name}</span>
      <span className="ml-2 font-mono text-sm font-semibold text-gray-900 bg-gray-100 px-2 py-1 border border-gray-300">
        {displayValue}
      </span>
    </div>
  );
}

function printBooleanProperty(name: string, value: boolean) {
  return (
    <div className="flex justify-between items-center py-2 px-3 bg-white border border-gray-200 w-full">
      <span className="text-gray-700 font-medium">{name}</span>
      <span
        className={`font-mono text-sm font-semibold px-2 py-1 border ${
          value
            ? "text-green-800 bg-green-100 border-green-300"
            : "text-red-800 bg-red-100 border-red-300"
        }`}
      >
        {value ? "✓ true" : "✗ false"}
      </span>
    </div>
  );
}

// packages/vue-example/src/views/BankDemo.vue
<template>
  <div class="max-w-6xl mx-auto space-y-8">
    <!-- Header -->
    <div class="text-center">
      <h1 class="text-4xl font-bold mb-4 bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
        🏦 FHE Bank Demo
      </h1>
      <p class="text-xl text-gray-600 mb-2">
        Confidential banking with encrypted deposits, withdrawals, and transfers
      </p>
      <p class="text-sm text-gray-500">
        Vue 3 + Composition API + Universal FHEVM SDK
      </p>
    </div>

    <!-- Wallet Connection -->
    <div v-if="!isConnected" class="card text-center">
      <div class="mb-4">
        <span class="inline-flex items-center justify-center w-16 h-16 rounded-full bg-blue-100 text-blue-600 text-4xl">
          🏦
        </span>
      </div>
      <h2 class="text-2xl font-bold text-gray-900 mb-2">Wallet not connected</h2>
      <p class="text-gray-600 mb-6">Connect your wallet to use the FHE Bank demo.</p>
      <button
        v-for="connector in connectors"
        :key="connector.id"
        @click="connect(connector.id)"
        class="btn-primary mr-2"
      >
        Connect {{ connector.name }}
      </button>
    </div>

    <!-- Main Demo -->
    <div v-else class="space-y-6">
      <!-- FHEVM Status -->
      <div class="card">
        <h3 class="text-xl font-bold mb-4 text-gray-900 border-b pb-2">🔧 Bank Status</h3>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div class="space-y-3">
            <div class="flex justify-between items-center py-2 px-3 bg-gray-50 rounded">
              <span class="font-medium">Status</span>
              <span :class="statusColor" class="font-mono text-sm">
                {{ statusMessage }}
              </span>
            </div>
            <div class="flex justify-between items-center py-2 px-3 bg-gray-50 rounded">
              <span class="font-medium">Ready</span>
              <span :class="isConnected ? 'text-green-600' : 'text-red-600'" class="font-mono text-sm">
                {{ isConnected ? '✅ Yes' : '❌ No' }}
              </span>
            </div>
            <div class="flex justify-between items-center py-2 px-3 bg-gray-50 rounded">
              <span class="font-medium">Wallet</span>
              <span class="font-mono text-sm">{{ address?.slice(0, 10) }}...</span>
            </div>
            <div class="flex justify-between items-center py-2 px-3 bg-gray-50 rounded">
              <span class="font-medium">Balance Handle</span>
              <span class="font-mono text-sm text-blue-600">
                {{ balanceHandle ? balanceHandle.toString().slice(0, 20) + '...' : 'None' }}
              </span>
            </div>
          </div>
          <div class="space-y-3">
            <div class="flex justify-between items-center py-2 px-3 bg-gray-50 rounded">
              <span class="font-medium">Chain ID</span>
              <span class="font-mono text-sm">{{ chainId || 'Unknown' }}</span>
            </div>
            <div class="flex justify-between items-center py-2 px-3 bg-gray-50 rounded">
              <span class="font-medium">Contract Address</span>
              <span class="font-mono text-sm text-green-600">
                {{ bankConfig.address?.slice(0, 10) }}...
              </span>
            </div>
            <div class="flex justify-between items-center py-2 px-3 bg-gray-50 rounded">
              <span class="font-medium">Decrypting</span>
              <span :class="isDecryptingSDK ? 'text-yellow-600' : 'text-gray-600'" class="font-mono text-sm">
                {{ isDecryptingSDK ? '⏳ Yes' : '✅ No' }}
              </span>
            </div>
            <div class="flex justify-between items-center py-2 px-3 bg-gray-50 rounded">
              <span class="font-medium">Error</span>
              <span class="font-mono text-sm text-red-600">
                {{ hasError ? state.error?.message : 'None' }}
              </span>
            </div>
          </div>
        </div>
      </div>

      <!-- Bank Operations -->
      <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <!-- Deposit -->
        <div class="card">
          <h3 class="text-xl font-bold mb-4 text-gray-900">💰 Deposit</h3>
          <div class="space-y-4">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Amount</label>
              <input
                v-model="amount"
                type="number"
                class="input"
                placeholder="Enter amount to deposit"
              />
            </div>
            <button
              @click="handleDeposit"
              :disabled="!isConnected || isProcessing"
              class="btn-success w-full"
            >
              <span v-if="isProcessing">⏳ Processing...</span>
              <span v-else>💰 Deposit</span>
            </button>
          </div>
        </div>

        <!-- Withdraw -->
        <div class="card">
          <h3 class="text-xl font-bold mb-4 text-gray-900">💸 Withdraw</h3>
          <div class="space-y-4">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Amount</label>
              <input
                v-model="amount"
                type="number"
                class="input"
                placeholder="Enter amount to withdraw"
              />
            </div>
            <button
              @click="handleWithdraw"
              :disabled="!isConnected || isProcessing"
              class="btn-danger w-full"
            >
              <span v-if="isProcessing">⏳ Processing...</span>
              <span v-else>💸 Withdraw</span>
            </button>
          </div>
        </div>

        <!-- Transfer -->
        <div class="card">
          <h3 class="text-xl font-bold mb-4 text-gray-900">🔄 Transfer</h3>
          <div class="space-y-4">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Recipient Address</label>
              <input
                v-model="recipient"
                type="text"
                class="input"
                placeholder="0x..."
              />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Amount</label>
              <input
                v-model="amount"
                type="number"
                class="input"
                placeholder="Enter amount to transfer"
              />
            </div>
            <button
              @click="handleTransfer"
              :disabled="!isConnected || isProcessing || !recipient"
              class="btn-primary w-full"
            >
              <span v-if="isProcessing">⏳ Processing...</span>
              <span v-else>🔄 Transfer</span>
            </button>
          </div>
        </div>

        <!-- View Balance -->
        <div class="card">
          <h3 class="text-xl font-bold mb-4 text-gray-900">👁️ View Balance</h3>
          <div class="space-y-4">
            <p class="text-gray-600">Decrypt your encrypted balance</p>
            <button
              @click="handleDecryptBalance"
              :disabled="!isConnected || isDecryptingSDK"
              class="btn-secondary w-full"
            >
              <span v-if="isDecryptingSDK">⏳ Decrypting...</span>
              <span v-else>👁️ Decrypt Balance</span>
            </button>
          </div>
        </div>
      </div>

      <!-- Balance Display -->
      <div class="card">
        <h3 class="text-xl font-bold mb-4 text-gray-900 border-b pb-2">💰 Your Balance</h3>
        <div class="text-center">
          <div class="text-6xl font-bold text-blue-600 mb-4">
            {{ decryptedValue !== null ? decryptedValue : '🔒' }}
          </div>
          <p class="text-gray-600 mb-4">
            {{ decryptedValue !== null ? 'Decrypted Balance' : 'Encrypted Balance (Click Decrypt to reveal)' }}
          </p>
          <div class="flex justify-center space-x-4">
            <button
              @click="handleDecryptBalance"
              :disabled="!isConnected || isDecryptingSDK || !balanceHandle"
              class="btn-success"
            >
              <span v-if="isDecryptingSDK">⏳ Decrypting...</span>
              <span v-else>🔓 Decrypt Balance</span>
            </button>
            <button
              @click="resetDecryptionState"
              :disabled="!isConnected"
              class="btn-warning"
            >
              🔄 Reset Decryption
            </button>
            <button
              @click="fetchBalanceHandle"
              :disabled="!isConnected"
              class="btn-secondary"
            >
              🔄 Get Balance
            </button>
          </div>
        </div>
      </div>



      <!-- Decryption Status -->
      <div v-if="decryptionMessage || decryptionError" class="card">
        <h3 class="text-xl font-bold mb-4 text-gray-900 border-b pb-2">🔓 Decryption Status</h3>
        <div class="space-y-3">
          <div v-if="decryptionMessage" class="flex justify-between items-center py-2 px-3 bg-blue-50 rounded">
            <span class="font-medium">Message</span>
            <span class="text-sm text-blue-600">{{ decryptionMessage }}</span>
          </div>
          <div v-if="decryptionError" class="flex justify-between items-center py-2 px-3 bg-red-50 rounded">
            <span class="font-medium">Error</span>
            <span class="text-sm text-red-600">{{ decryptionError }}</span>
          </div>
          <div class="flex justify-between items-center py-2 px-3 bg-gray-50 rounded">
            <span class="font-medium">Can Decrypt</span>
            <span :class="canDecrypt ? 'text-green-600' : 'text-red-600'" class="text-sm">
              {{ canDecrypt ? '✅ Yes' : '❌ No' }}
            </span>
          </div>
        </div>
      </div>

      <!-- Transaction Status -->
      <div v-if="isWritePending" class="bg-blue-50 border border-blue-200 p-4 rounded-lg">
        <h3 class="font-bold text-blue-800 text-lg mb-2">⏳ Transaction Pending</h3>
        <p class="text-blue-700">Your transaction is being processed. Please wait...</p>
      </div>

      <!-- Transaction Success -->
      <div v-if="isWriteSuccess" class="bg-green-50 border border-green-200 p-4 rounded-lg">
        <h3 class="font-bold text-green-800 text-lg mb-2">✅ Transaction Successful</h3>
        <p class="text-green-700">Your transaction has been confirmed on the blockchain!</p>
      </div>

      <!-- Errors -->
      <div v-if="hasError || encryptError || signatureError || writeError" class="bg-red-50 border border-red-200 p-4 rounded-lg">
        <h3 class="font-bold text-red-800 text-lg mb-2">❌ Errors</h3>
        <div class="space-y-2">
          <p v-if="hasError" class="text-red-700">FHEVM: {{ state.error?.message }}</p>
          <p v-if="encryptError" class="text-red-700">Encrypt: {{ encryptError.message }}</p>
          <p v-if="signatureError" class="text-red-700">Signature: {{ signatureError.message }}</p>
          <p v-if="writeError" class="text-red-700">Transaction: {{ writeError.message }}</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { useFHEVM, useFHEVMSignature, useFHEDecrypt, useInMemoryStorage, logger } from '@fhevm/sdk/vue'
import { useWallet } from '@/composables/useWallet'
import { getContractConfig } from '@/contracts'
import { useReadContract, useWriteContract } from '@wagmi/vue'
import { ethers } from 'ethers'

const { isConnected, address, chainId, connect, connectors } = useWallet()

const ethersSigner = computed(() => {
  if (!isConnected.value || !address.value) return undefined
  
  try {
    const provider = new ethers.BrowserProvider((window as any).ethereum)
    const signer = new ethers.JsonRpcSigner(provider, address.value)
    
    return signer
  } catch (error) {
    logger.error('Failed to create ethers signer', error)
    return undefined
  }
})

const bankConfig = getContractConfig('FHEBank')

const fhevmConfig = {
  rpcUrl: import.meta.env.VITE_RPC_URL || `https://sepolia.infura.io/v3/${import.meta.env.VITE_INFURA_API_KEY}`,
  chainId: Number(import.meta.env.VITE_CHAIN_ID) || 11155111,
  mockChains: {
    31337: "http://localhost:8545"
  }
}

const { 
  state, 
  isReady: isFHEVMConnected, 
  hasError, 
  isInitializing: isLoading
} = useFHEVM(fhevmConfig)

const statusMessage = computed(() => {
  switch (state.value.status) {
    case 'idle': return 'Initializing...'
    case 'loading': return 'Loading FHEVM...'
    case 'ready': return 'Ready'
    case 'error': return 'Error'
    default: return 'Unknown'
  }
})

const statusColor = computed(() => {
  switch (state.value.status) {
    case 'ready': return 'text-green-600'
    case 'error': return 'text-red-600'
    case 'loading': return 'text-yellow-600'
    default: return 'text-gray-600'
  }
})

const balanceHandle = ref<string | null>(null)

const { data: fetchedBalance, refetch: refetchBalance, error: fetchError } = useReadContract({
  address: computed(() => bankConfig.address as `0x${string}` | undefined),
  abi: bankConfig.abi as any,
  functionName: 'getEncryptedBalance',
  args: [address.value!],
  query: {
    enabled: false, 
    refetchOnWindowFocus: false,
  },
})

watch(fetchedBalance, (newBalance) => {
  if (newBalance) {
    balanceHandle.value = newBalance as string
  }
})

watch(fetchError, (error) => {
  if (error) {
    logger.error("Bank Fetch error", error)
  }
})

const fetchBalanceHandle = async () => {
  if (!bankConfig.address || !isFHEVMConnected.value || !address.value) {
    return
  }
  
  try {
    await refetchBalance()
  } catch (error) {
    logger.error("Failed to fetch balance handle", error)
  }
}

const { 
  writeContract: writeBank, 
  isPending: isWritePending, 
  error: writeError,
  isSuccess: isWriteSuccess,
  reset: resetWrite
} = useWriteContract()

const { 
  generateSignature, 
  signature, 
  isSigning, 
  error: signatureError 
} = useFHEVMSignature(computed(() => state.value.instance), address)
const fhevmDecryptionSignatureStorage = useInMemoryStorage()

const requests = computed(() => {
  if (!bankConfig.address || !balanceHandle.value || balanceHandle.value === ethers.ZeroHash) return undefined
  return [{ handle: balanceHandle.value.toString(), contractAddress: bankConfig.address as `0x${string}` }] as const
})

const { 
  canDecrypt,
  decrypt: performDecrypt,
  isDecrypting: isDecryptingSDK,
  message: decryptionMessage,
  results,
  error: decryptionError
} = useFHEDecrypt({
  instance: computed(() => state.value.instance),
  ethersSigner: computed(() => ethersSigner.value),
  fhevmDecryptionSignatureStorage: fhevmDecryptionSignatureStorage.storage.value,
  requests: requests
})

const resetDecryptionState = () => {
  isDecryptingSDK.value = false
  decryptionError.value = null
  decryptionMessage.value = "Ready to decrypt"
}

watch([() => state.value.instance, ethersSigner, requests, canDecrypt], () => {
  logger.debug('Bank Dependencies check', {
    instance: !!state.value.instance,
    ethersSigner: !!ethersSigner.value,
    ethersSignerType: typeof ethersSigner.value,
    ethersSignerValue: ethersSigner.value,
    chainId: chainId.value,
    requests: requests.value,
    requestsLength: requests.value?.length,
    canDecrypt: canDecrypt.value,
    missingDependencies: {
      instance: !state.value.instance ? 'MISSING' : 'OK',
      signer: !ethersSigner.value ? 'MISSING' : 'OK', 
      requests: !requests.value || requests.value.length <= 0 ? 'MISSING' : 'OK'
    }
  })
}, { immediate: true })

const isEncrypting = ref(false)
const encryptError = ref<Error | null>(null)

const message = ref<string>("")
const isProcessing = ref(false)
const amount = ref<string>("100")
const recipient = ref<string>("")

const decryptedValue = computed(() => {
  if (!balanceHandle.value) {
    return null
  }
  
  if (balanceHandle.value === ethers.ZeroHash) {
    return 0
  }
  
  const handleKey = balanceHandle.value.toString()
  const clear = results.value?.[handleKey]
  
  if (typeof clear === "undefined") {
    return null
  }
  
  return Number(clear)
})

const isDecrypted = computed(() => {
  return Boolean(balanceHandle.value && decryptedValue.value !== null)
})

const handleDeposit = async () => {
  if (!isConnected.value || !bankConfig.address) return
  
  isProcessing.value = true
  message.value = "💰 Depositing to bank..."

  try {
    const expectedChainId = 11155111 // Sepolia
    if (chainId.value !== expectedChainId) {
      message.value = `⚠️ Wrong network! Please switch to Sepolia (Chain ID: ${expectedChainId}). Current: ${chainId.value}`
      return
    }

    if (!state.value.instance) {
      throw new Error("FHEVM instance not ready")
    }
    
    message.value = "🔐 Creating encrypted input..."
    
    let externalEuint64: string
    let inputProof: string
    
    try {
      const userAddress = address.value!
      const input = state.value.instance.createEncryptedInput(bankConfig.address, userAddress)
      input.add64(parseInt(amount.value)) 
      const encryptedResult = await input.encrypt()
      
      
      if (!encryptedResult || !encryptedResult.handles || !encryptedResult.handles[0]) {
        throw new Error("Encryption failed - no handle returned")
      }
      
      if (!encryptedResult.inputProof) {
        throw new Error("Encryption failed - no inputProof returned")
      }
      
      message.value = `🔐 Encrypted: ${encryptedResult.handles[0].toString().slice(0, 20)}...`
      
      const toHex = (data: Uint8Array) => {
        if (!data || !Array.isArray(Array.from(data))) {
          throw new Error("Invalid data for hex conversion")
        }
        return '0x' + Array.from(data).map(b => b.toString(16).padStart(2, '0')).join('')
      }
      
      externalEuint64 = toHex(encryptedResult.handles[0])
      inputProof = toHex(encryptedResult.inputProof)
      
      
    } catch (encryptError) {
      logger.error("Bank Encryption error", encryptError)
      throw new Error(`Encryption failed: ${encryptError instanceof Error ? encryptError.message : String(encryptError)}`)
    }
    
    message.value = "📝 Signing transaction..."
    
    resetWrite()
    
    try {
      const txResult = await writeBank({
      address: bankConfig.address as `0x${string}`,
      abi: bankConfig.abi as any,
      functionName: 'deposit',
        args: [externalEuint64, inputProof], // Hex strings for externalEuint64 and bytes
      })
      
      message.value = "⏳ Waiting for transaction confirmation..."
      
      await new Promise(resolve => setTimeout(resolve, 2000))
      
      message.value = "✅ Deposit completed! Refreshing balance..."
      await fetchBalanceHandle()
      
    } catch (txError) {
      logger.error("Bank Transaction error", txError)
      throw new Error(`Transaction failed: ${txError instanceof Error ? txError.message : String(txError)}`)
    }
  } catch (error) {
    message.value = `❌ Deposit failed: ${error instanceof Error ? error.message : String(error)}`
    logger.error("Bank Deposit error", error)
  } finally {
    isProcessing.value = false
  }
}

const handleWithdraw = async () => {
  if (!isConnected.value || !bankConfig.address) return
  
  isProcessing.value = true
  message.value = "💸 Withdrawing from bank..."
  
  try {
    if (!state.value.instance) {
      throw new Error("FHEVM instance not ready")
    }
    
    message.value = "🔐 Creating encrypted input..."
    
    let externalEuint64: string
    let inputProof: string
    
    try {
      const userAddress = address.value!
      const input = state.value.instance.createEncryptedInput(bankConfig.address, userAddress)
      input.add64(parseInt(amount.value)) 
      const encryptedResult = await input.encrypt()
      
      
      if (!encryptedResult || !encryptedResult.handles || !encryptedResult.handles[0]) {
        throw new Error("Encryption failed - no handle returned")
      }
      
      if (!encryptedResult.inputProof) {
        throw new Error("Encryption failed - no inputProof returned")
      }
      
      message.value = `🔐 Encrypted: ${encryptedResult.handles[0].toString().slice(0, 20)}...`
      
      const toHex = (data: Uint8Array) => {
        if (!data || !Array.isArray(Array.from(data))) {
          throw new Error("Invalid data for hex conversion")
        }
        return '0x' + Array.from(data).map(b => b.toString(16).padStart(2, '0')).join('')
      }
      
      externalEuint64 = toHex(encryptedResult.handles[0])
      inputProof = toHex(encryptedResult.inputProof)
      
      
    } catch (encryptError) {
      logger.error("Bank Encryption error", encryptError)
      throw new Error(`Encryption failed: ${encryptError instanceof Error ? encryptError.message : String(encryptError)}`)
    }
    
    message.value = "📝 Signing transaction..."
    
    resetWrite()
    
    try {
      const txResult = await writeBank({
      address: bankConfig.address as `0x${string}`,
      abi: bankConfig.abi as any,
      functionName: 'withdraw',
        args: [externalEuint64, inputProof], // Hex strings for externalEuint64 and bytes
      })
      
      message.value = "⏳ Waiting for transaction confirmation..."
      
      await new Promise(resolve => setTimeout(resolve, 2000))
      
      message.value = "✅ Withdrawal completed! Refreshing balance..."
      
      await fetchBalanceHandle()
      
    } catch (txError) {
      logger.error("Bank Transaction error", txError)
      throw new Error(`Transaction failed: ${txError instanceof Error ? txError.message : String(txError)}`)
    }
  } catch (error) {
    message.value = `❌ Withdrawal failed: ${error instanceof Error ? error.message : String(error)}`
    logger.error("Bank Withdrawal error", error)
  } finally {
    isProcessing.value = false
  }
}

const handleTransfer = async () => {
  if (!isConnected.value || !recipient.value || !bankConfig.address) return
  
  isProcessing.value = true
  message.value = "🔄 Transferring funds..."
  
  try {
    const amountNum = parseInt(amount.value)
    if (isNaN(amountNum) || amountNum <= 0) {
      message.value = "Please enter a valid amount"
      return
    }

    if (!recipient.value.startsWith("0x") || recipient.value.length !== 42) {
      message.value = "Please enter a valid recipient address"
      return
    }

    if (!state.value.instance) {
      throw new Error("FHEVM instance not ready")
    }
    
    message.value = "🔐 Creating encrypted input..."
    
    let externalEuint64: string
    let inputProof: string
    
    try {
      const userAddress = address.value!
      const input = state.value.instance.createEncryptedInput(bankConfig.address, userAddress)
      input.add64(parseInt(amount.value)) 
      const encryptedResult = await input.encrypt()
      
      
      if (!encryptedResult || !encryptedResult.handles || !encryptedResult.handles[0]) {
        throw new Error("Encryption failed - no handle returned")
      }
      
      if (!encryptedResult.inputProof) {
        throw new Error("Encryption failed - no inputProof returned")
      }
      
      message.value = `🔐 Encrypted: ${encryptedResult.handles[0].toString().slice(0, 20)}...`
      
      const toHex = (data: Uint8Array) => {
        if (!data || !Array.isArray(Array.from(data))) {
          throw new Error("Invalid data for hex conversion")
        }
        return '0x' + Array.from(data).map(b => b.toString(16).padStart(2, '0')).join('')
      }
      
      externalEuint64 = toHex(encryptedResult.handles[0])
      inputProof = toHex(encryptedResult.inputProof)
      
      
    } catch (encryptError) {
      logger.error("Bank Encryption error", encryptError)
      throw new Error(`Encryption failed: ${encryptError instanceof Error ? encryptError.message : String(encryptError)}`)
    }
    
    message.value = "📝 Signing transaction..."
    
    resetWrite()
    
    try {
      const txResult = await writeBank({
      address: bankConfig.address as `0x${string}`,
      abi: bankConfig.abi as any,
      functionName: 'transfer',
        args: [recipient.value, externalEuint64, inputProof], 
      })
      
      message.value = "⏳ Waiting for transaction confirmation..."
      
      await new Promise(resolve => setTimeout(resolve, 2000))
      
      message.value = "✅ Transfer completed! Refreshing balance..."
      
      await fetchBalanceHandle()
      
    } catch (txError) {
      logger.error("Bank Transaction error", txError)
      throw new Error(`Transaction failed: ${txError instanceof Error ? txError.message : String(txError)}`)
    }
  } catch (error) {
    message.value = `❌ Transfer failed: ${error instanceof Error ? error.message : String(error)}`
    logger.error("Bank Transfer error", error)
  } finally {
    isProcessing.value = false
  }
}

const handleDecryptBalance = async () => {
  if (!balanceHandle.value) {
    message.value = "⚠️ No balance data to decrypt"
    return
  }

  if (!canDecrypt.value) {
    message.value = "⚠️ Cannot decrypt - missing dependencies (signer, instance, or requests)"
    return
  }

  try {
    await performDecrypt()
    
    await new Promise(resolve => setTimeout(resolve, 100))
    
    if (decryptedValue.value === null) {
      logger.warn("Bank Decryption returned null", { results: results.value })
    }
    
    message.value = `✅ Balance decryption completed! Value: ${decryptedValue.value}`
    
  } catch (error) {
    message.value = `❌ Balance decryption failed: ${error instanceof Error ? error.message : String(error)}`
    logger.error("Bank Decryption error", error)
  }
}

onMounted(() => {
})
</script>
